id: P28824CD0
initial_creation_type: input
source_metadata:
  title: Gampopa Series
  language: en
  description: 'Texts by and about Gampopa Sonam Rinchen (sgam po pa bsod nams rin
    chen, 1079–1153), the famous master credited with founding the Kagyü school of
    Tibetan Buddhism:'
  volume:
    aac4542472b246f59c014f51c1e76506:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      parent: Guru Yoga
    55fbf170945c48148b8a9d0df54aad56:
      title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
      parent: Guru Yoga
    393fc1f40e984381b3fcb1b7c02126b4:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Guru Yoga
    d639a6da1d82487c8fa211fa8b1bff0f:
      title: 'A Precious Garland for the Supreme Path of the Three Types of Individual:
        The Root of Dakpo''s Four Dharmas'
      parent: Lamrim
    129b926da77b4f41b7749e24638c97b8:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      parent: Prayers
created_at: '2022-02-28T23:21:13.676086'
last_modified_at: '2022-02-28T23:21:13.676092'
